<a href="https://colab.research.google.com/github/JuanMosa/Mexico-s-CPI-and-PIBE-performance./blob/main/IPC_PIBE_Mexico.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import yfinance as yf

In [ ]:
ticker="^MXX" #Ticker from Yahoo finance
start_date="1994-12-01"#Zedillo's first day as president
end_date="2026-06-10" #Current date

In [ ]:
ipc=yf.download(ticker,start_date,end_date)

/tmp/ipykernel_10118/3771265642.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  ipc=yf.download(ticker,start_date,end_date)
[*********************100%***********************]  1 of 1 completed

In [ ]:
ipc.head()

Price             Close         High          Low         Open Volume
Ticker             ^MXX         ^MXX         ^MXX         ^MXX   ^MXX
Date
1994-12-02  2537.500000  2591.300049  2522.399902  2591.300049      0
1994-12-05  2521.399902  2547.399902  2510.500000  2537.500000      0
1994-12-06  2514.399902  2521.699951  2507.399902  2521.399902      0
1994-12-07  2520.899902  2532.000000  2514.100098  2514.399902      0
1994-12-08  2499.899902  2528.000000  2495.000000  2520.899902      0

In [ ]:
#yfinance downlload the data in multiindex columns, so we reset index
#for a future analysis, date will become a normal column
ipc=ipc.reset_index()

In [ ]:
ipc.head()

Price        Date        Close         High          Low         Open Volume
Ticker                    ^MXX         ^MXX         ^MXX         ^MXX   ^MXX
0      1994-12-02  2537.500000  2591.300049  2522.399902  2591.300049      0
1      1994-12-05  2521.399902  2547.399902  2510.500000  2537.500000      0
2      1994-12-06  2514.399902  2521.699951  2507.399902  2521.399902      0
3      1994-12-07  2520.899902  2532.000000  2514.100098  2514.399902      0
4      1994-12-08  2499.899902  2528.000000  2495.000000  2520.899902      0

In [ ]:
ipc.tail()

Price,Date,Close,High,Low,Open,Volume
Ticker,,^MXX,^MXX,^MXX,^MXX,^MXX
7900,2026-06-03,68285.820312,68963.093750,68187.421875,68809.242188,191614200
7901,2026-06-04,67392.187500,68331.507812,67197.617188,68331.507812,170681200
7902,2026-06-05,66141.382812,67142.781250,65955.406250,67142.781250,197106100
7903,2026-06-08,65698.101562,66420.726562,65594.671875,66247.617188,168173800
7904,2026-06-09,65409.480469,66480.023438,64666.238281,66049.921875,197644400

In [ ]:
ipc= ipc.drop(columns=["High","Low","Open","Volume"])

/tmp/ipykernel_10118/1415377795.py:1: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  ipc= ipc.drop(columns=["High","Low","Open","Volume"])

In [ ]:
#Rename
ipc=ipc.rename(columns={"Close":"Price"})

In [ ]:
ipc.head()

Price        Date        Price
Ticker                    ^MXX
0      1994-12-02  2537.500000
1      1994-12-05  2521.399902
2      1994-12-06  2514.399902
3      1994-12-07  2520.899902
4      1994-12-08  2499.899902

In [ ]:
#let's separate each president period
#Create a function
def separated_periods(date):
  if date >=pd.Timestamp ("1995-01-01") and date <=pd.Timestamp ("2000-12-31"):
    return "Ernesto Zedillo"
  elif date >=pd.Timestamp ("2001-01-01") and date <=pd.Timestamp ("2006-12-31"):
    return "Vicente Fox"
  elif date >=pd.Timestamp ("2007-01-01") and date <=pd.Timestamp ("2012-12-31"):
    return "Felipe Calderón"
  elif date >=pd.Timestamp ("2013-01-01") and date <=pd.Timestamp ("2018-12-31"):
    return "Peña Nieto"
  elif date >=pd.Timestamp ("2019-01-01") and date <=pd.Timestamp ("2024-12-31"):
    return "AMLO"
  elif date >=pd.Timestamp ("2025-01-01") and date <=pd.Timestamp ("2026-06-10"): #Current date
    return "Claudia Sheinbaum"
  else:
    return "0"

I needed to add pandas timestamp becasue python read the date's function as str

In [ ]:
#check data type
print(ipc["Date"].dtype)

datetime64[ns]

In [ ]:
#creating a new column
ipc["President"] =ipc["Date"].apply(separated_periods)

In [ ]:
ipc.head()

Price        Date        Price President
Ticker                    ^MXX
0      1994-12-02  2537.500000         0
1      1994-12-05  2521.399902         0
2      1994-12-06  2514.399902         0
3      1994-12-07  2520.899902         0
4      1994-12-08  2499.899902         0

In [ ]:
ipc.tail()

Price        Date         Price          President
Ticker                     ^MXX
7900   2026-06-03  68285.820312  Claudia Sheinbaum
7901   2026-06-04  67392.187500  Claudia Sheinbaum
7902   2026-06-05  66141.382812  Claudia Sheinbaum
7903   2026-06-08  65698.101562  Claudia Sheinbaum
7904   2026-06-09  65409.480469  Claudia Sheinbaum

In [ ]:
#Download the data
ipc.to_csv("IPC_And_MXPresidents.csv", index=False) #index false remove column numbers

# **Now we will work with the data gathered from INEGI**

In [ ]:
PIBE_per_state= pd.read_excel("/content/PIBE_r_1.xlsx")

In [ ]:
PIBE_per_state.head(10)

,Instituto Nacional de Estadística y Geografía (INEGI).,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45
0,Sistema de Cuentas Nacionales de México. Produ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,PIB de las actividades económicas por entidad ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Concepto,1.980000e+03,1.981000e+03,1.982000e+03,1.983000e+03,1.984000e+03,1.985000e+03,1.986000e+03,1.987000e+03,1.988000e+03,...,2.015000e+03,2.016000e+03,2.017000e+03,2.018000e+03,2.019000e+03,2.020000e+03,2.021000e+03,2.022000e+03,2023 R,2024 P
4,Millones de pesos a precios de 2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,"____aProducto interno bruto, a precios de mercado",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Estados Unidos Mexicanos,1.051603e+07,1.152408e+07,1.151836e+07,1.098574e+07,1.137172e+07,1.158996e+07,1.113448e+07,1.136423e+07,1.150267e+07,...,2.286815e+07,2.327349e+07,2.370911e+07,2.417667e+07,2.408173e+07,2.206993e+07,2.340483e+07,2.427309e+07,25027209.096,25365220.652
7,Aguascalientes,7.447883e+04,8.281606e+04,8.313348e+04,7.880057e+04,8.246682e+04,8.498015e+04,8.160273e+04,8.437908e+04,8.648220e+04,...,2.944972e+05,3.073958e+05,3.142424e+05,3.279263e+05,3.293584e+05,3.071257e+05,3.152331e+05,3.146022e+05,334314.666,328087.965
8,Baja California,4.001570e+05,4.516768e+05,4.467815e+05,4.062001e+05,4.254886e+05,4.375292e+05,4.022752e+05,4.143618e+05,4.178160e+05,...,7.950807e+05,8.286922e+05,8.636006e+05,8.788169e+05,8.939462e+05,8.396933e+05,8.963136e+05,9.193003e+05,947957.519,947677.009
9,Baja California Sur,5.301591e+04,5.773620e+04,5.818820e+04,5.723282e+04,5.939146e+04,6.073952e+04,5.987933e+04,6.132662e+04,6.234741e+04,...,1.560720e+05,1.630946e+05,1.707844e+05,1.846181e+05,1.778608e+05,1.519313e+05,1.710646e+05,1.781298e+05,180788.204,187152.161

In [ ]:
PIBE_per_state =PIBE_per_state.drop([0,1,2,4,5])
PIBE_per_state.head()

,Instituto Nacional de Estadística y Geografía (INEGI).,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45
3,Concepto,1.980000e+03,1.981000e+03,1.982000e+03,1.983000e+03,1.984000e+03,1.985000e+03,1.986000e+03,1.987000e+03,1.988000e+03,...,2.015000e+03,2.016000e+03,2.017000e+03,2.018000e+03,2.019000e+03,2.020000e+03,2.021000e+03,2.022000e+03,2023 R,2024 P
6,Estados Unidos Mexicanos,1.051603e+07,1.152408e+07,1.151836e+07,1.098574e+07,1.137172e+07,1.158996e+07,1.113448e+07,1.136423e+07,1.150267e+07,...,2.286815e+07,2.327349e+07,2.370911e+07,2.417667e+07,2.408173e+07,2.206993e+07,2.340483e+07,2.427309e+07,25027209.096,25365220.652
7,Aguascalientes,7.447883e+04,8.281606e+04,8.313348e+04,7.880057e+04,8.246682e+04,8.498015e+04,8.160273e+04,8.437908e+04,8.648220e+04,...,2.944972e+05,3.073958e+05,3.142424e+05,3.279263e+05,3.293584e+05,3.071257e+05,3.152331e+05,3.146022e+05,334314.666,328087.965
8,Baja California,4.001570e+05,4.516768e+05,4.467815e+05,4.062001e+05,4.254886e+05,4.375292e+05,4.022752e+05,4.143618e+05,4.178160e+05,...,7.950807e+05,8.286922e+05,8.636006e+05,8.788169e+05,8.939462e+05,8.396933e+05,8.963136e+05,9.193003e+05,947957.519,947677.009
9,Baja California Sur,5.301591e+04,5.773620e+04,5.818820e+04,5.723282e+04,5.939146e+04,6.073952e+04,5.987933e+04,6.132662e+04,6.234741e+04,...,1.560720e+05,1.630946e+05,1.707844e+05,1.846181e+05,1.778608e+05,1.519313e+05,1.710646e+05,1.781298e+05,180788.204,187152.161

In [ ]:
PIBE_per_state.head(100)

,Instituto Nacional de Estadística y Geografía (INEGI).,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45
3,Concepto,1.980000e+03,1.981000e+03,1.982000e+03,1.983000e+03,1.984000e+03,1.985000e+03,1.986000e+03,1.987000e+03,1.988000e+03,...,2.015000e+03,2.016000e+03,2.017000e+03,2.018000e+03,2.019000e+03,2.020000e+03,2.021000e+03,2.022000e+03,2023 R,2024 P
6,Estados Unidos Mexicanos,1.051603e+07,1.152408e+07,1.151836e+07,1.098574e+07,1.137172e+07,1.158996e+07,1.113448e+07,1.136423e+07,1.150267e+07,...,2.286815e+07,2.327349e+07,2.370911e+07,2.417667e+07,2.408173e+07,2.206993e+07,2.340483e+07,2.427309e+07,25027209.096,25365220.652
7,Aguascalientes,7.447883e+04,8.281606e+04,8.313348e+04,7.880057e+04,8.246682e+04,8.498015e+04,8.160273e+04,8.437908e+04,8.648220e+04,...,2.944972e+05,3.073958e+05,3.142424e+05,3.279263e+05,3.293584e+05,3.071257e+05,3.152331e+05,3.146022e+05,334314.666,328087.965
8,Baja California,4.001570e+05,4.516768e+05,4.467815e+05,4.062001e+05,4.254886e+05,4.375292e+05,4.022752e+05,4.143618e+05,4.178160e+05,...,7.950807e+05,8.286922e+05,8.636006e+05,8.788169e+05,8.939462e+05,8.396933e+05,8.963136e+05,9.193003e+05,947957.519,947677.009
9,Baja California Sur,5.301591e+04,5.773620e+04,5.818820e+04,5.723282e+04,5.939146e+04,6.073952e+04,5.987933e+04,6.132662e+04,6.234741e+04,...,1.560720e+05,1.630946e+05,1.707844e+05,1.846181e+05,1.778608e+05,1.519313e+05,1.710646e+05,1.781298e+05,180788.204,187152.161
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,San Luis Potosí,1.770753e+00,1.774663e+00,1.768202e+00,1.752650e+00,1.753167e+00,1.754592e+00,1.746048e+00,1.750298e+00,1.753774e+00,...,2.099096e+00,2.173529e+00,2.278634e+00,2.307166e+00,2.219076e+00,2.266662e+00,2.205489e+00,2.194995e+00,2.291894,2.285162
101,Sinaloa,2.429146e+00,2.407510e+00,2.407470e+00,2.450233e+00,2.440572e+00,2.447038e+00,2.473689e+00,2.476353e+00,2.468318e+00,...,2.121646e+00,2.180557e+00,2.187781e+00,2.182741e+00,2.169040e+00,2.194627e+00,2.168052e+00,2.127126e+00,2.06616,2.027916
102,Sonora,2.954322e+00,2.996234e+00,2.974964e+00,2.899843e+00,2.912383e+00,2.936155e+00,2.867533e+00,2.878598e+00,2.863102e+00,...,3.323534e+00,3.403161e+00,3.309283e+00,3.234927e+00,3.251857e+00,3.313277e+00,3.251167e+00,3.254813e+00,3.304014,3.242853
103,Tabasco,2.568623e+00,2.553380e+00,2.557069e+00,2.563850e+00,2.568597e+00,2.582260e+00,2.619593e+00,2.639535e+00,2.667080e+00,...,2.419435e+00,2.289424e+00,2.118810e+00,1.950497e+00,1.851491e+00,2.105854e+00,2.330355e+00,2.627499e+00,2.586695,2.38597
104,Tamaulipas,2.868588e+00,2.871557e+00,2.875678e+00,2.850707e+00,2.868971e+00,2.904465e+00,2.898230e+00,2.921167e+00,2.928930e+00,...,3.117860e+00,3.050508e+00,2.991043e+00,3.028099e+00,3.126077e+00,3.132769e+00,3.097778e+00,3.085196e+00,2.981218,3.014899

In [ ]:
PIBE_per_state.shape

(183, 46)

In [ ]:
PIBE_per_state.iloc[:34]

,Instituto Nacional de Estadística y Geografía (INEGI).,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45
3,Concepto,1.980000e+03,1.981000e+03,1.982000e+03,1.983000e+03,1.984000e+03,1.985000e+03,1.986000e+03,1.987000e+03,1.988000e+03,...,2.015000e+03,2.016000e+03,2.017000e+03,2.018000e+03,2.019000e+03,2.020000e+03,2.021000e+03,2.022000e+03,2023 R,2024 P
6,Estados Unidos Mexicanos,1.051603e+07,1.152408e+07,1.151836e+07,1.098574e+07,1.137172e+07,1.158996e+07,1.113448e+07,1.136423e+07,1.150267e+07,...,2.286815e+07,2.327349e+07,2.370911e+07,2.417667e+07,2.408173e+07,2.206993e+07,2.340483e+07,2.427309e+07,25027209.096,25365220.652
7,Aguascalientes,7.447883e+04,8.281606e+04,8.313348e+04,7.880057e+04,8.246682e+04,8.498015e+04,8.160273e+04,8.437908e+04,8.648220e+04,...,2.944972e+05,3.073958e+05,3.142424e+05,3.279263e+05,3.293584e+05,3.071257e+05,3.152331e+05,3.146022e+05,334314.666,328087.965
8,Baja California,4.001570e+05,4.516768e+05,4.467815e+05,4.062001e+05,4.254886e+05,4.375292e+05,4.022752e+05,4.143618e+05,4.178160e+05,...,7.950807e+05,8.286922e+05,8.636006e+05,8.788169e+05,8.939462e+05,8.396933e+05,8.963136e+05,9.193003e+05,947957.519,947677.009
9,Baja California Sur,5.301591e+04,5.773620e+04,5.818820e+04,5.723282e+04,5.939146e+04,6.073952e+04,5.987933e+04,6.132662e+04,6.234741e+04,...,1.560720e+05,1.630946e+05,1.707844e+05,1.846181e+05,1.778608e+05,1.519313e+05,1.710646e+05,1.781298e+05,180788.204,187152.161
10,Campeche,5.113623e+05,5.609713e+05,5.597220e+05,5.231345e+05,5.461992e+05,5.663784e+05,5.486499e+05,5.703912e+05,5.880265e+05,...,7.003107e+05,6.632392e+05,5.956670e+05,5.645911e+05,5.419629e+05,5.005147e+05,4.896043e+05,4.726800e+05,508514.617,473399.457
11,Coahuila de Zaragoza,3.622988e+05,4.014199e+05,4.009474e+05,3.722965e+05,3.881558e+05,3.997794e+05,3.759492e+05,3.846357e+05,3.877812e+05,...,8.977021e+05,9.017195e+05,9.415818e+05,9.660547e+05,9.533843e+05,8.435976e+05,9.215870e+05,9.358412e+05,927968.193,922286.189
12,Colima,6.371501e+04,6.900193e+04,6.959367e+04,6.802628e+04,7.050103e+04,7.248765e+04,7.137544e+04,7.330839e+04,7.461404e+04,...,1.410291e+05,1.407052e+05,1.503601e+05,1.538084e+05,1.611099e+05,1.481433e+05,1.476673e+05,1.484384e+05,153354.778,157139.889
13,Chiapas,2.000615e+05,2.120223e+05,2.138021e+05,2.114672e+05,2.174135e+05,2.219245e+05,2.210170e+05,2.259788e+05,2.303215e+05,...,3.640013e+05,3.699193e+05,3.597344e+05,3.536001e+05,3.489144e+05,3.372404e+05,3.536385e+05,3.745180e+05,379626.199,389794.852
14,Chihuahua,3.031899e+05,3.361435e+05,3.345206e+05,3.156095e+05,3.279389e+05,3.361246e+05,3.183348e+05,3.251302e+05,3.265954e+05,...,8.038833e+05,8.304885e+05,8.512843e+05,8.533228e+05,8.668613e+05,8.087109e+05,8.460639e+05,9.112711e+05,940100.509,930854.91
15,Ciudad de México,1.831599e+06,2.023098e+06,2.017376e+06,1.937032e+06,1.992079e+06,1.989028e+06,1.890532e+06,1.896703e+06,1.897079e+06,...,3.503520e+06,3.571368e+06,3.646318e+06,3.694575e+06,3.679917e+06,3.293855e+06,3.496056e+06,3.650378e+06,3805614.443,3885956.593
16,Durango,1.381317e+05,1.496223e+05,1.488645e+05,1.423743e+05,1.465418e+05,1.493313e+05,1.444110e+05,1.473196e+05,1.491357e+05,...,3.002894e+05,3.053822e+05,3.046467e+05,3.089813e+05,3.094264e+05,2.862408e+05,3.032514e+05,3.004781e+05,309199.136,323802.357
17,Guanajuato,3.682131e+05,4.054384e+05,4.058440e+05,3.869767e+05,4.018025e+05,4.110547e+05,3.952237e+05,4.048265e+05,4.105827e+05,...,1.026150e+06,1.064743e+06,1.115371e+06,1.120603e+06,1.099063e+06,1.019446e+06,1.084518e+06,1.110919e+06,1125731.16,1170675.898
18,Guerrero,1.937750e+05,2.032657e+05,2.042313e+05,2.011025e+05,2.050974e+05,2.079640e+05,2.053552e+05,2.081605e+05,2.101910e+05,...,3.141037e+05,3.134221e+05,3.085680e+05,3.178449e+05,3.171468e+05,2.899682e+05,3.036334e+05,3.101059e+05,310655.381,314019.724
19,Hidalgo,2.113765e+05,2.317283e+05,2.319404e+05,2.196711e+05,2.279939e+05,2.341553e+05,2.253466e+05,2.312051e+05,2.351798e+05,...,4.139092e+05,4.184663e+05,4.164086e+05,4.186304e+05,4.092664e+05,3.649398e+05,3.919620e+05,4.312519e+05,441544.349,454116.317
20,Jalisco,7.702766e+05,8.426300e+05,8.423293e+05,8.038367e+05,8.316138e+05,8.481025e+05,8.164194e+05,8.336125e+05,8.439572e+05,...,1.626751e+06,1.676419e+06,1.708140e+06,1.754180e+06,1.767123e+06,1.624209e+06,1.712483e+06,1.797547e+06,1849621.221,1864059.172
21,México,9.377051e+05,1.021972e+06,1.020963e+06,9.756809e+05,1.005942e+06,1.019988e+06,9.794954e+05,9.951293e+05,1.005116e+06,...,2.007572e+06,2.058753e+06,2.166132e+06,2.243798e+06,2.209647e+06,2.035392e+06,2.163538e+06,2.218453e+06,2266285.482,2313164.328
22,Michoacán de Ocampo,2.601811e+05,2.795194e+05,2.826634e+05,2.776607e+05,2.872799e+05,2.948930e+05,2.914918e+05,2.990337e+05,3.045481e+05,...,5.735059e+05,5.914095e+05,6.103944e+05,6.337566e+05,6.356282e+05,6.011887e+05,6.290662e+05,6.520668e+05,676492.511,681445.83
23,Morelos,1.302126e+05,1.405426e+05,1.406925e+05,1.352968e+05,1.396361e+05,1.427643e+05,1.390690e+05,1.423510e+05,1.448242e+05,...,2.657509e+05,2.743649e+05,2.774028e+05,2.732446e+05,2.696860e+05,2.449888e+05,2.599385e+05,2.601195e+05,267785.129,271218.84
24,Nayarit,7.866080e+04,8.547637e+04,8.567290e+04,8.310188e+04,8.577044e+04,8.740463e+04,8.485490e+04,8.663684e+04,8.765918e+04,...,1.474288e+05,1.525859e+05,1.551104e+05,1.557575e+05,1.571633e+05,1.426052e+05,1.559687e+05,1.626010e+05,162089.928,159749.672
25,Nuevo León,6.179911e+05,6.885510e+05,6.897486e+05,6.509821e+05,6.801036e+05,6.974568e+05,6.653051e+05,6.830979e+05,6.944877e+05,...,1.728164e+06,1.743961e+06,1.809344e+06,1.909026e+06,1.918825e+06,1.743166e+06,1.865875e+06,1.928658e+06,1991519.7,2059995.565
26,Oaxaca,2.447412e+05,2.620073e+05,2.624547e+05,2.542057e+05,2.613297e+05,2.664219e+05,2.604317e+05,2.655008e+05,2.687848e+05,...,4.014040e+05,3.997679e+05,3.582364e+05,3.831596e+05,3.673636e+05,3.509114e+05,3.854181e+05,4.155027e+05,443373.204,467374.413
27,Puebla,3.083972e+05,3.360570e+05,3.363324e+05,3.201611e+05,3.322135e+05,3.411158e+05,3.294374e+05,3.387834e+05,3.449905e+05,...,7.656500e+05,7.815111e+05,8.353687e+05,8.495560e+05,8.569107e+05,7.672101e+05,7.948762e+05,8.258028e+05,852715.662,882359.631
28,Querétaro,1.755619e+05,1.984789e+05,1.971835e+05,1.798147e+05,1.886264e+05,1.946423e+05,1.812945e+05,1.868812e+05,1.898485e+05,...,5.745782e+05,5.767348e+05,5.914153e+05,6.113678e+05,6.091083e+05,5.536139e+05,5.781751e+05,5.892212e+05,613534.714,621620.129
29,Quintana Roo,9.170347e+04,9.998022e+04,9.939022e+04,9.547836e+04,9.861155e+04,1.000147e+05,9.731634e+04,9.992501e+04,1.025170e+05,...,3.186078e+05,3.397334e+05,3.571168e+05,3.773407e+05,3.767573e+05,2.927334e+05,3.325421e+05,3.567276e+05,398839.252,383116.448
30,San Luis Potosí,1.862129e+05,2.045136e+05,2.036679e+05,1.925416e+05,1.993652e+05,2.033566e+05,1.944134e+05,1.989078e+05,2.017309e+05,...,4.800246e+05,5.058561e+05,5.402437e+05,5.577960e+05,5.343919e+05,5.002509e+05,5.161910e+05,5.327932e+05,573596.989,579636.262
31,Sinaloa,2.554497e+05,2.774434e+05,2.773011e+05,2.691762e+05,2.775349e+05,2.836108e+05,2.754324e+05,2.814184e+05,2.839225e+05,...,4.851812e+05,5.074918e+05,5.187033e+05,5.277141e+05,5.223425e+05,4.843527e+05,5.074290e+05,5.163193e+05,517102.253,514385.484
32,Sonora,3.106774e+05,3.452883e+05,3.426672e+05,3.185692e+05,3.311878e+05,3.402993e+05,3.192849e+05,3.271304e+05,3.293333e+05,...,7.600310e+05,7.920343e+05,7.846014e+05,7.820977e+05,7.831035e+05,7.312380e+05,7.609301e+05,7.900437e+05,826902.615,822556.904
33,Tabasco,2.701171e+05,2.942535e+05,2.945325e+05,2.816579e+05,2.920935e+05,2.992830e+05,2.916781e+05,2.999628e+05,3.067855e+05,...,5.532801e+05,5.328289e+05,5.023510e+05,4.715652e+05,4.458710e+05,4.647606e+05,5.454158e+05,6.377752e+05,647377.607,605206.515
34,Tamaulipas,3.016615e+05,3.309205e+05,3.312311e+05,3.131713e+05,3.262512e+05,3.366265e+05,3.227029e+05,3.319680e+05,3.369052e+05,...,7.129971e+05,7.099597e+05,7.091495e+05,7.320936e+05,7.528135e+05,6.914000e+05,7.250296e+05,7.488726e+05,746115.755,764735.773
35,Tlaxcala,6.246165e+04,6.801869e+04,6.823790e+04,6.565145e+04,6.793715e+04,6.947017e+04,6.756343e+04,6.899890e+04,6.999949e+04,...,1.370537e+05,1.391678e+05,1.439204e+05,1.477529e+05,1.478768e+05,1.350832e+05,1.432133e+05,1.466416e+05,149204.433,151512.669
36,Veracruz de Ignacio de la Llave,5.981514e+05,6.428162e+05,6.461011e+05,6.309699e+05,6.501950e+05,6.633222e+05,6.522685e+05,6.659772e+05,6.761358e+05,...,1.082922e+06,1.059514e+06,1.032744e+06,1.029905e+06,1.053328e+06,9.712521e+05,1.027896e+06,1.041978e+06,1062248.661,1094822.174
37,Yucatán,1.288582e+05,1.398141e+05,1.404243e+05,1.363858e+05,1.409161e+05,1.436854e+05,1.403086e+05,1.433372e+05,1.455052e+05,...,3.220981e+05,3.361077e+05,3.495990e+05,3.647979e+05,3.658258e+05,3.335282e+05,3.586598e+05,3.690433e+05,387739.307,402785.746
38,Zacatecas,7.563411e+04,8.085552e+04,8.182668e+04,8.147409e+04,8.403777e+04,8.602878e+04,8.576215e+04,8.784780e+04,8.946940e+04,...,2.146055e+05,2.166546e+05,2.205680e+05,2.283882e+05,2.197465e+05,2.106431e+05,2.215923e+05,2.250133e+05,229295.519,240511.776

In [ ]:
PIBE_per_state = PIBE_per_state.iloc[:34]

In [ ]:
PIBE_per_state.head(50)

,Instituto Nacional de Estadística y Geografía (INEGI).,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45
3,Concepto,1.980000e+03,1.981000e+03,1.982000e+03,1.983000e+03,1.984000e+03,1.985000e+03,1.986000e+03,1.987000e+03,1.988000e+03,...,2.015000e+03,2.016000e+03,2.017000e+03,2.018000e+03,2.019000e+03,2.020000e+03,2.021000e+03,2.022000e+03,2023 R,2024 P
6,Estados Unidos Mexicanos,1.051603e+07,1.152408e+07,1.151836e+07,1.098574e+07,1.137172e+07,1.158996e+07,1.113448e+07,1.136423e+07,1.150267e+07,...,2.286815e+07,2.327349e+07,2.370911e+07,2.417667e+07,2.408173e+07,2.206993e+07,2.340483e+07,2.427309e+07,25027209.096,25365220.652
7,Aguascalientes,7.447883e+04,8.281606e+04,8.313348e+04,7.880057e+04,8.246682e+04,8.498015e+04,8.160273e+04,8.437908e+04,8.648220e+04,...,2.944972e+05,3.073958e+05,3.142424e+05,3.279263e+05,3.293584e+05,3.071257e+05,3.152331e+05,3.146022e+05,334314.666,328087.965
8,Baja California,4.001570e+05,4.516768e+05,4.467815e+05,4.062001e+05,4.254886e+05,4.375292e+05,4.022752e+05,4.143618e+05,4.178160e+05,...,7.950807e+05,8.286922e+05,8.636006e+05,8.788169e+05,8.939462e+05,8.396933e+05,8.963136e+05,9.193003e+05,947957.519,947677.009
9,Baja California Sur,5.301591e+04,5.773620e+04,5.818820e+04,5.723282e+04,5.939146e+04,6.073952e+04,5.987933e+04,6.132662e+04,6.234741e+04,...,1.560720e+05,1.630946e+05,1.707844e+05,1.846181e+05,1.778608e+05,1.519313e+05,1.710646e+05,1.781298e+05,180788.204,187152.161
10,Campeche,5.113623e+05,5.609713e+05,5.597220e+05,5.231345e+05,5.461992e+05,5.663784e+05,5.486499e+05,5.703912e+05,5.880265e+05,...,7.003107e+05,6.632392e+05,5.956670e+05,5.645911e+05,5.419629e+05,5.005147e+05,4.896043e+05,4.726800e+05,508514.617,473399.457
11,Coahuila de Zaragoza,3.622988e+05,4.014199e+05,4.009474e+05,3.722965e+05,3.881558e+05,3.997794e+05,3.759492e+05,3.846357e+05,3.877812e+05,...,8.977021e+05,9.017195e+05,9.415818e+05,9.660547e+05,9.533843e+05,8.435976e+05,9.215870e+05,9.358412e+05,927968.193,922286.189
12,Colima,6.371501e+04,6.900193e+04,6.959367e+04,6.802628e+04,7.050103e+04,7.248765e+04,7.137544e+04,7.330839e+04,7.461404e+04,...,1.410291e+05,1.407052e+05,1.503601e+05,1.538084e+05,1.611099e+05,1.481433e+05,1.476673e+05,1.484384e+05,153354.778,157139.889
13,Chiapas,2.000615e+05,2.120223e+05,2.138021e+05,2.114672e+05,2.174135e+05,2.219245e+05,2.210170e+05,2.259788e+05,2.303215e+05,...,3.640013e+05,3.699193e+05,3.597344e+05,3.536001e+05,3.489144e+05,3.372404e+05,3.536385e+05,3.745180e+05,379626.199,389794.852
14,Chihuahua,3.031899e+05,3.361435e+05,3.345206e+05,3.156095e+05,3.279389e+05,3.361246e+05,3.183348e+05,3.251302e+05,3.265954e+05,...,8.038833e+05,8.304885e+05,8.512843e+05,8.533228e+05,8.668613e+05,8.087109e+05,8.460639e+05,9.112711e+05,940100.509,930854.91
15,Ciudad de México,1.831599e+06,2.023098e+06,2.017376e+06,1.937032e+06,1.992079e+06,1.989028e+06,1.890532e+06,1.896703e+06,1.897079e+06,...,3.503520e+06,3.571368e+06,3.646318e+06,3.694575e+06,3.679917e+06,3.293855e+06,3.496056e+06,3.650378e+06,3805614.443,3885956.593
16,Durango,1.381317e+05,1.496223e+05,1.488645e+05,1.423743e+05,1.465418e+05,1.493313e+05,1.444110e+05,1.473196e+05,1.491357e+05,...,3.002894e+05,3.053822e+05,3.046467e+05,3.089813e+05,3.094264e+05,2.862408e+05,3.032514e+05,3.004781e+05,309199.136,323802.357
17,Guanajuato,3.682131e+05,4.054384e+05,4.058440e+05,3.869767e+05,4.018025e+05,4.110547e+05,3.952237e+05,4.048265e+05,4.105827e+05,...,1.026150e+06,1.064743e+06,1.115371e+06,1.120603e+06,1.099063e+06,1.019446e+06,1.084518e+06,1.110919e+06,1125731.16,1170675.898
18,Guerrero,1.937750e+05,2.032657e+05,2.042313e+05,2.011025e+05,2.050974e+05,2.079640e+05,2.053552e+05,2.081605e+05,2.101910e+05,...,3.141037e+05,3.134221e+05,3.085680e+05,3.178449e+05,3.171468e+05,2.899682e+05,3.036334e+05,3.101059e+05,310655.381,314019.724
19,Hidalgo,2.113765e+05,2.317283e+05,2.319404e+05,2.196711e+05,2.279939e+05,2.341553e+05,2.253466e+05,2.312051e+05,2.351798e+05,...,4.139092e+05,4.184663e+05,4.164086e+05,4.186304e+05,4.092664e+05,3.649398e+05,3.919620e+05,4.312519e+05,441544.349,454116.317
20,Jalisco,7.702766e+05,8.426300e+05,8.423293e+05,8.038367e+05,8.316138e+05,8.481025e+05,8.164194e+05,8.336125e+05,8.439572e+05,...,1.626751e+06,1.676419e+06,1.708140e+06,1.754180e+06,1.767123e+06,1.624209e+06,1.712483e+06,1.797547e+06,1849621.221,1864059.172
21,México,9.377051e+05,1.021972e+06,1.020963e+06,9.756809e+05,1.005942e+06,1.019988e+06,9.794954e+05,9.951293e+05,1.005116e+06,...,2.007572e+06,2.058753e+06,2.166132e+06,2.243798e+06,2.209647e+06,2.035392e+06,2.163538e+06,2.218453e+06,2266285.482,2313164.328
22,Michoacán de Ocampo,2.601811e+05,2.795194e+05,2.826634e+05,2.776607e+05,2.872799e+05,2.948930e+05,2.914918e+05,2.990337e+05,3.045481e+05,...,5.735059e+05,5.914095e+05,6.103944e+05,6.337566e+05,6.356282e+05,6.011887e+05,6.290662e+05,6.520668e+05,676492.511,681445.83
23,Morelos,1.302126e+05,1.405426e+05,1.406925e+05,1.352968e+05,1.396361e+05,1.427643e+05,1.390690e+05,1.423510e+05,1.448242e+05,...,2.657509e+05,2.743649e+05,2.774028e+05,2.732446e+05,2.696860e+05,2.449888e+05,2.599385e+05,2.601195e+05,267785.129,271218.84
24,Nayarit,7.866080e+04,8.547637e+04,8.567290e+04,8.310188e+04,8.577044e+04,8.740463e+04,8.485490e+04,8.663684e+04,8.765918e+04,...,1.474288e+05,1.525859e+05,1.551104e+05,1.557575e+05,1.571633e+05,1.426052e+05,1.559687e+05,1.626010e+05,162089.928,159749.672
25,Nuevo León,6.179911e+05,6.885510e+05,6.897486e+05,6.509821e+05,6.801036e+05,6.974568e+05,6.653051e+05,6.830979e+05,6.944877e+05,...,1.728164e+06,1.743961e+06,1.809344e+06,1.909026e+06,1.918825e+06,1.743166e+06,1.865875e+06,1.928658e+06,1991519.7,2059995.565
26,Oaxaca,2.447412e+05,2.620073e+05,2.624547e+05,2.542057e+05,2.613297e+05,2.664219e+05,2.604317e+05,2.655008e+05,2.687848e+05,...,4.014040e+05,3.997679e+05,3.582364e+05,3.831596e+05,3.673636e+05,3.509114e+05,3.854181e+05,4.155027e+05,443373.204,467374.413
27,Puebla,3.083972e+05,3.360570e+05,3.363324e+05,3.201611e+05,3.322135e+05,3.411158e+05,3.294374e+05,3.387834e+05,3.449905e+05,...,7.656500e+05,7.815111e+05,8.353687e+05,8.495560e+05,8.569107e+05,7.672101e+05,7.948762e+05,8.258028e+05,852715.662,882359.631
28,Querétaro,1.755619e+05,1.984789e+05,1.971835e+05,1.798147e+05,1.886264e+05,1.946423e+05,1.812945e+05,1.868812e+05,1.898485e+05,...,5.745782e+05,5.767348e+05,5.914153e+05,6.113678e+05,6.091083e+05,5.536139e+05,5.781751e+05,5.892212e+05,613534.714,621620.129
29,Quintana Roo,9.170347e+04,9.998022e+04,9.939022e+04,9.547836e+04,9.861155e+04,1.000147e+05,9.731634e+04,9.992501e+04,1.025170e+05,...,3.186078e+05,3.397334e+05,3.571168e+05,3.773407e+05,3.767573e+05,2.927334e+05,3.325421e+05,3.567276e+05,398839.252,383116.448
30,San Luis Potosí,1.862129e+05,2.045136e+05,2.036679e+05,1.925416e+05,1.993652e+05,2.033566e+05,1.944134e+05,1.989078e+05,2.017309e+05,...,4.800246e+05,5.058561e+05,5.402437e+05,5.577960e+05,5.343919e+05,5.002509e+05,5.161910e+05,5.327932e+05,573596.989,579636.262
31,Sinaloa,2.554497e+05,2.774434e+05,2.773011e+05,2.691762e+05,2.775349e+05,2.836108e+05,2.754324e+05,2.814184e+05,2.839225e+05,...,4.851812e+05,5.074918e+05,5.187033e+05,5.277141e+05,5.223425e+05,4.843527e+05,5.074290e+05,5.163193e+05,517102.253,514385.484
32,Sonora,3.106774e+05,3.452883e+05,3.426672e+05,3.185692e+05,3.311878e+05,3.402993e+05,3.192849e+05,3.271304e+05,3.293333e+05,...,7.600310e+05,7.920343e+05,7.846014e+05,7.820977e+05,7.831035e+05,7.312380e+05,7.609301e+05,7.900437e+05,826902.615,822556.904
33,Tabasco,2.701171e+05,2.942535e+05,2.945325e+05,2.816579e+05,2.920935e+05,2.992830e+05,2.916781e+05,2.999628e+05,3.067855e+05,...,5.532801e+05,5.328289e+05,5.023510e+05,4.715652e+05,4.458710e+05,4.647606e+05,5.454158e+05,6.377752e+05,647377.607,605206.515
34,Tamaulipas,3.016615e+05,3.309205e+05,3.312311e+05,3.131713e+05,3.262512e+05,3.366265e+05,3.227029e+05,3.319680e+05,3.369052e+05,...,7.129971e+05,7.099597e+05,7.091495e+05,7.320936e+05,7.528135e+05,6.914000e+05,7.250296e+05,7.488726e+05,746115.755,764735.773
35,Tlaxcala,6.246165e+04,6.801869e+04,6.823790e+04,6.565145e+04,6.793715e+04,6.947017e+04,6.756343e+04,6.899890e+04,6.999949e+04,...,1.370537e+05,1.391678e+05,1.439204e+05,1.477529e+05,1.478768e+05,1.350832e+05,1.432133e+05,1.466416e+05,149204.433,151512.669
36,Veracruz de Ignacio de la Llave,5.981514e+05,6.428162e+05,6.461011e+05,6.309699e+05,6.501950e+05,6.633222e+05,6.522685e+05,6.659772e+05,6.761358e+05,...,1.082922e+06,1.059514e+06,1.032744e+06,1.029905e+06,1.053328e+06,9.712521e+05,1.027896e+06,1.041978e+06,1062248.661,1094822.174
37,Yucatán,1.288582e+05,1.398141e+05,1.404243e+05,1.363858e+05,1.409161e+05,1.436854e+05,1.403086e+05,1.433372e+05,1.455052e+05,...,3.220981e+05,3.361077e+05,3.495990e+05,3.647979e+05,3.658258e+05,3.335282e+05,3.586598e+05,3.690433e+05,387739.307,402785.746
38,Zacatecas,7.563411e+04,8.085552e+04,8.182668e+04,8.147409e+04,8.403777e+04,8.602878e+04,8.576215e+04,8.784780e+04,8.946940e+04,...,2.146055e+05,2.166546e+05,2.205680e+05,2.283882e+05,2.197465e+05,2.106431e+05,2.215923e+05,2.250133e+05,229295.519,240511.776

In [ ]:
PIBE_per_state.columns

Index(['Instituto Nacional de Estadística y Geografía (INEGI).', 'Unnamed: 1',
       'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35',
       'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
       'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43',
       'Unnamed: 44', 'Unnamed: 45'],
      dtype='object')

In [ ]:
#We should convert the row 'Concepto' to header
print(PIBE_per_state.iloc[0])
PIBE_per_state.columns = PIBE_per_state.iloc[0]

Instituto Nacional de Estadística y Geografía (INEGI).    Concepto
Unnamed: 1                                                  1980.0
Unnamed: 2                                                  1981.0
Unnamed: 3                                                  1982.0
Unnamed: 4                                                  1983.0
Unnamed: 5                                                  1984.0
Unnamed: 6                                                  1985.0
Unnamed: 7                                                  1986.0
Unnamed: 8                                                  1987.0
Unnamed: 9                                                  1988.0
Unnamed: 10                                                 1989.0
Unnamed: 11                                                 1990.0
Unnamed: 12                                                 1991.0
Unnamed: 13                                                 1992.0
Unnamed: 14                                                 1993.0
Unnamed: 15                                                 1994.0
Unnamed: 16                                                 1995.0
Unnamed: 17                                                 1996.0
Unnamed: 18                                                 1997.0
Unnamed: 19                                                 1998.0
Unnamed: 20                                                 1999.0
Unnamed: 21                                                 2000.0
Unnamed: 22                                                 2001.0
Unnamed: 23                                                 2002.0
Unnamed: 24                                                 2003.0
Unnamed: 25                                                 2004.0
Unnamed: 26                                                 2005.0
Unnamed: 27                                                 2006.0
Unnamed: 28                                                 2007.0
Unnamed: 29                                                 2008.0
Unnamed: 30                                                 2009.0
Unnamed: 31                                                 2010.0
Unnamed: 32                                                 2011.0
Unnamed: 33                                                 2012.0
Unnamed: 34                                                 2013.0
Unnamed: 35                                                 2014.0
Unnamed: 36                                                 2015.0
Unnamed: 37                                                 2016.0
Unnamed: 38                                                 2017.0
Unnamed: 39                                                 2018.0
Unnamed: 40                                                 2019.0
Unnamed: 41                                                 2020.0
Unnamed: 42                                                 2021.0
Unnamed: 43                                                 2022.0
Unnamed: 44                                                 2023 R
Unnamed: 45                                                 2024 P
Name: 3, dtype: object

In [ ]:
PIBE_per_state.head()

3,Concepto,1980.0,1981.0,1982.0,1983.0,1984.0,1985.0,1986.0,1987.0,1988.0,...,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,2023 R,2024 P
3,Concepto,1.980000e+03,1.981000e+03,1.982000e+03,1.983000e+03,1.984000e+03,1.985000e+03,1.986000e+03,1.987000e+03,1.988000e+03,...,2.015000e+03,2.016000e+03,2.017000e+03,2.018000e+03,2.019000e+03,2.020000e+03,2.021000e+03,2.022000e+03,2023 R,2024 P
6,Estados Unidos Mexicanos,1.051603e+07,1.152408e+07,1.151836e+07,1.098574e+07,1.137172e+07,1.158996e+07,1.113448e+07,1.136423e+07,1.150267e+07,...,2.286815e+07,2.327349e+07,2.370911e+07,2.417667e+07,2.408173e+07,2.206993e+07,2.340483e+07,2.427309e+07,25027209.096,25365220.652
7,Aguascalientes,7.447883e+04,8.281606e+04,8.313348e+04,7.880057e+04,8.246682e+04,8.498015e+04,8.160273e+04,8.437908e+04,8.648220e+04,...,2.944972e+05,3.073958e+05,3.142424e+05,3.279263e+05,3.293584e+05,3.071257e+05,3.152331e+05,3.146022e+05,334314.666,328087.965
8,Baja California,4.001570e+05,4.516768e+05,4.467815e+05,4.062001e+05,4.254886e+05,4.375292e+05,4.022752e+05,4.143618e+05,4.178160e+05,...,7.950807e+05,8.286922e+05,8.636006e+05,8.788169e+05,8.939462e+05,8.396933e+05,8.963136e+05,9.193003e+05,947957.519,947677.009
9,Baja California Sur,5.301591e+04,5.773620e+04,5.818820e+04,5.723282e+04,5.939146e+04,6.073952e+04,5.987933e+04,6.132662e+04,6.234741e+04,...,1.560720e+05,1.630946e+05,1.707844e+05,1.846181e+05,1.778608e+05,1.519313e+05,1.710646e+05,1.781298e+05,180788.204,187152.161

In [ ]:
PIBE_per_state_long = PIBE_per_state.melt(id_vars = 'Concepto')
PIBE_per_state_long.head(100)

                                          Concepto       3         value
0                                         Concepto  1980.0        1980.0
1                         Estados Unidos Mexicanos  1980.0  10516029.242
2                                   Aguascalientes  1980.0     74478.826
3                                  Baja California  1980.0    400156.971
4                              Baja California Sur  1980.0     53015.906
..                                             ...     ...           ...
95                                          Sonora  1982.0    342667.231
96                                         Tabasco  1982.0    294532.487
97                                      Tamaulipas  1982.0    331231.125
98                                        Tlaxcala  1982.0     68237.902
99                 Veracruz de Ignacio de la Llave  1982.0    646101.093

[100 rows x 3 columns]

In [ ]:
#change the name of columns
PIBE_per_state_long = PIBE_per_state.melt(id_vars='Concepto',var_name='Year',value_name='Price').rename(columns={'Concepto':'State'})
PIBE_per_state_long.head()

                                     State    Year         Price
0                                 Concepto  1980.0        1980.0
1                 Estados Unidos Mexicanos  1980.0  10516029.242
2                           Aguascalientes  1980.0     74478.826
3                          Baja California  1980.0    400156.971
4                      Baja California Sur  1980.0     53015.906

In [ ]:
PIBE_per_state_long.drop([0])

                                               State    Year         Price
1                           Estados Unidos Mexicanos  1980.0  10516029.242
2                                     Aguascalientes  1980.0     74478.826
3                                    Baja California  1980.0    400156.971
4                                Baja California Sur  1980.0     53015.906
5                                           Campeche  1980.0    511362.336
...                                              ...     ...           ...
1525                                      Tamaulipas  2024 P    764735.773
1526                                        Tlaxcala  2024 P    151512.669
1527                 Veracruz de Ignacio de la Llave  2024 P   1094822.174
1528                                         Yucatán  2024 P    402785.746
1529                                       Zacatecas  2024 P    240511.776

[1529 rows x 3 columns]

https://www.youtube.com/watch?v=DCqWZ0DGVqw
Video for melt function
https://pandas.pydata.org/docs/reference/api/pandas.melt.html

In [ ]:
def separated_periods_PIBE(Year):
  if Year >=1995 and Year <=2000:
    return "Ernesto Zedillo"
  elif Year >=2001 and Year <=2006:
    return "Vicente Fox"
  elif Year >=2007 and Year <=2012:
    return "Felipe Calderón"
  elif Year >=2013 and Year <=2018:
    return "Peña Nieto"
  elif Year >=2019 and Year <=2024:
    return "AMLO"
  elif  Year >=2025 and Year <=2026: #Current date
    return "Claudia Sheinbaum"
  else:
    return "No data"

In [ ]:
PIBE_per_state_long["Year"].dtype

dtype('O')

In [ ]:
PIBE_per_state_long['Year'].unique()

array([np.float64(1980.0), np.float64(1981.0), np.float64(1982.0),
       np.float64(1983.0), np.float64(1984.0), np.float64(1985.0),
       np.float64(1986.0), np.float64(1987.0), np.float64(1988.0),
       np.float64(1989.0), np.float64(1990.0), np.float64(1991.0),
       np.float64(1992.0), np.float64(1993.0), np.float64(1994.0),
       np.float64(1995.0), np.float64(1996.0), np.float64(1997.0),
       np.float64(1998.0), np.float64(1999.0), np.float64(2000.0),
       np.float64(2001.0), np.float64(2002.0), np.float64(2003.0),
       np.float64(2004.0), np.float64(2005.0), np.float64(2006.0),
       np.float64(2007.0), np.float64(2008.0), np.float64(2009.0),
       np.float64(2010.0), np.float64(2011.0), np.float64(2012.0),
       np.float64(2013.0), np.float64(2014.0), np.float64(2015.0),
       np.float64(2016.0), np.float64(2017.0), np.float64(2018.0),
       np.float64(2019.0), np.float64(2020.0), np.float64(2021.0),
       np.float64(2022.0), '2023 R', '2024 P'], dtype=object)

In [ ]:
#We need to delete R and P from 2023 and 2024, then change the data tpye to int
PIBE_per_state_long["Year"] = (
    PIBE_per_state_long["Year"].astype(str)
    .str.replace(" R", "", regex=False)
    .str.replace(" P", "", regex=False))
#Convert to int
PIBE_per_state_long["Year"] = (
    pd.to_numeric(PIBE_per_state_long["Year"])
    .astype(int))

In [ ]:
print(PIBE_per_state_long["Year"].dtype)
print(PIBE_per_state_long["Year"].unique())

int64
[1980 1981 1982 1983 1984 1985 1986 1987 1988 1989 1990 1991 1992 1993
 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007
 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021
 2022 2023 2024]

In [ ]:
PIBE_per_state_long["President"]=PIBE_per_state_long["Year"].apply(separated_periods_PIBE)

In [ ]:
PIBE_per_state_long.tail(50)

,State,Year,Price,President
1480,Morelos,2023,267785.129,AMLO
1481,Nayarit,2023,162089.928,AMLO
1482,Nuevo León,2023,1991519.7,AMLO
1483,Oaxaca,2023,443373.204,AMLO
1484,Puebla,2023,852715.662,AMLO
1485,Querétaro,2023,613534.714,AMLO
1486,Quintana Roo,2023,398839.252,AMLO
1487,San Luis Potosí,2023,573596.989,AMLO
1488,Sinaloa,2023,517102.253,AMLO
1489,Sonora,2023,826902.615,AMLO
1490,Tabasco,2023,647377.607,AMLO
1491,Tamaulipas,2023,746115.755,AMLO
1492,Tlaxcala,2023,149204.433,AMLO
1493,Veracruz de Ignacio de la Llave,2023,1062248.661,AMLO
1494,Yucatán,2023,387739.307,AMLO
1495,Zacatecas,2023,229295.519,AMLO
1496,Concepto,2024,2024 P,AMLO
1497,Estados Unidos Mexicanos,2024,25365220.652,AMLO
1498,Aguascalientes,2024,328087.965,AMLO
1499,Baja California,2024,947677.009,AMLO
1500,Baja California Sur,2024,187152.161,AMLO
1501,Campeche,2024,473399.457,AMLO
1502,Coahuila de Zaragoza,2024,922286.189,AMLO
1503,Colima,2024,157139.889,AMLO
1504,Chiapas,2024,389794.852,AMLO
1505,Chihuahua,2024,930854.91,AMLO
1506,Ciudad de México,2024,3885956.593,AMLO
1507,Durango,2024,323802.357,AMLO
1508,Guanajuato,2024,1170675.898,AMLO
1509,Guerrero,2024,314019.724,AMLO
1510,Hidalgo,2024,454116.317,AMLO
1511,Jalisco,2024,1864059.172,AMLO
1512,México,2024,2313164.328,AMLO
1513,Michoacán de Ocampo,2024,681445.83,AMLO
1514,Morelos,2024,271218.84,AMLO
1515,Nayarit,2024,159749.672,AMLO
1516,Nuevo León,2024,2059995.565,AMLO
1517,Oaxaca,2024,467374.413,AMLO
1518,Puebla,2024,882359.631,AMLO
1519,Querétaro,2024,621620.129,AMLO
1520,Quintana Roo,2024,383116.448,AMLO
1521,San Luis Potosí,2024,579636.262,AMLO
1522,Sinaloa,2024,514385.484,AMLO
1523,Sonora,2024,822556.904,AMLO
1524,Tabasco,2024,605206.515,AMLO
1525,Tamaulipas,2024,764735.773,AMLO
1526,Tlaxcala,2024,151512.669,AMLO
1527,Veracruz de Ignacio de la Llave,2024,1094822.174,AMLO
1528,Yucatán,2024,402785.746,AMLO
1529,Zacatecas,2024,240511.776,AMLO

In [ ]:
#Remove blank spaces in price
PIBE_per_state_long = PIBE_per_state_long.dropna(subset=['Price'])

In [ ]:
PIBE_per_state_long['State'].unique()

array(['Concepto', '               Estados Unidos Mexicanos',
       '               Aguascalientes', '               Baja California',
       '               Baja California Sur', '               Campeche',
       '               Coahuila de Zaragoza', '               Colima',
       '               Chiapas', '               Chihuahua',
       '               Ciudad de México', '               Durango',
       '               Guanajuato', '               Guerrero',
       '               Hidalgo', '               Jalisco',
       '               México', '               Michoacán de Ocampo',
       '               Morelos', '               Nayarit',
       '               Nuevo León', '               Oaxaca',
       '               Puebla', '               Querétaro',
       '               Quintana Roo', '               San Luis Potosí',
       '               Sinaloa', '               Sonora',
       '               Tabasco', '               Tamaulipas',
       '               Tlaxcala',
       '               Veracruz de Ignacio de la Llave',
       '               Yucatán', '               Zacatecas'], dtype=object)

In [ ]:
#Delete leading spaces
PIBE_per_state_long["State"] = (PIBE_per_state_long["State"].str.strip())

In [ ]:
#Drop values from state Concepto and  Estados Unidos Mexicanos
PIBE_per_state_long = PIBE_per_state_long[~PIBE_per_state_long['State'].isin(['Concepto', 'Estados Unidos Mexicanos'])]

In [ ]:
PIBE_per_state_long.to_csv('PIBE_per_state.csv',index=False)

In [ ]:
#i want to analyse the data with the growth per state for each presidental period
#I'm going to create a the grwoth and append it into new data
PIBE_per_state_long = PIBE_per_state_long.sort_values(
    ["State", "Year"])

In [ ]:
growth = (
    PIBE_per_state_long.groupby(['President','State'])
    .agg(Start = ('Price','first'),
    End=('Price','last')).reset_index()
    )

In [ ]:
#Calculate the growth
growth['GrowthPerState']=(
    (growth['End']- growth['Start'])/growth['Start']
) *100

In [ ]:
growth.head(100)

,President,State,Start,End,GrowthPerState
0,AMLO,Aguascalientes,329358.364,328087.965,-0.385719
1,AMLO,Baja California,893946.249,947677.009,6.010514
2,AMLO,Baja California Sur,177860.75,187152.161,5.223981
3,AMLO,Campeche,541962.926,473399.457,-12.650952
4,AMLO,Chiapas,348914.392,389794.852,11.716473
...,...,...,...,...,...
95,Felipe Calderón,Zacatecas,165494.332,201298.32,21.634571
96,No data,Aguascalientes,74478.826,121683.61,63.38014
97,No data,Baja California,400156.971,548270.478,37.013851
98,No data,Baja California Sur,53015.906,75145.064,41.740601
99,No data,Campeche,511362.336,713798.595,39.587636

In [ ]:
growth.shape

(192, 5)

In [ ]:
growth.to_csv("growth_by_president_state.csv", index=False)